# Generated by Django 5.2.7 on 2025-10-31 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_CCPP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ccpp', models.CharField(max_length=150, unique=True, verbose_name='ID CCPP')),
                ('nombre', models.CharField(max_length=150, verbose_name='CCPP Residencial')),
                ('fecha_entrega', models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega')),
                ('cantidad_anios', models.IntegerField(default=0, verbose_name='Cantidad de Años')),
                ('periodo', models.CharField(max_length=10, verbose_name='Período')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección de la CCPP')),
                ('habilitada', models.BooleanField(default=True, verbose_name='CCPP Habilitada')),
                ('operario_comunidad', models.TextField(blank=True, verbose_name='Operario Comunidad')),
                ('empresa_especializada', models.TextField(blank=True, verbose_name='Empresa Especializada')),
                ('administracion_edificio', models.TextField(blank=True, verbose_name='Administración del Edificio')),
                ('tecnico_especialista', models.TextField(blank=True, verbose_name='Técnico Especialista')),
                ('tecnico_cabecera', models.TextField(blank=True, verbose_name='Técnico de Cabecera')),
                ('copia_oculta', models.TextField(blank=True, verbose_name='Copia Oculta (Contactos)')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capitulo', models.CharField(max_length=255, verbose_name='Capitulo')),
                ('unidad', models.CharField(max_length=255, verbose_name='Unidad')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripcion')),
                ('observacion', models.CharField(max_length=255, verbose_name='Observacion')),
                ('doc', models.CharField(max_length=255, verbose_name='DOC')),
            ],
        ),
    ]
