# Generated by Django 5.2.7 on 2025-11-01 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdministrador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_CCPP_Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccpp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdministrador.tbl_ccpp', verbose_name='CCPP')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdministrador.tbl_unidad', verbose_name='Unidad')),
            ],
        ),
    ]
