# Generated by Django 5.2.7 on 2025-11-02 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAdministrador', '0002_tbl_ccpp_unidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_ccpp',
            name='periodo',
        ),
    ]
