# Generated by Django 5.2.7 on 2025-11-06 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdministrador', '0003_remove_tbl_ccpp_periodo'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Correo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=255, verbose_name='Asunto')),
                ('cuerpo', models.TextField(verbose_name='Cuerpo del Correo')),
            ],
        ),
    ]
