# Generated by Django 5.2.7 on 2025-11-06 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdministrador', '0004_tbl_correo'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_inspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_inspeccion', models.CharField(max_length=100, unique=True, verbose_name='Código de Inspección')),
                ('nombre_inspeccion', models.CharField(max_length=255, verbose_name='Nombre de la Inspección')),
                ('descripcion_inspeccion', models.CharField(max_length=255, verbose_name='Descripción de la Inspección')),
                ('notificacionA_inspeccion', models.BooleanField(default=False, verbose_name='Notificación')),
            ],
        ),
    ]
