# Generated by Django 5.2.7 on 2025-11-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdministrador', '0005_tbl_inspeccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_inspeccion',
            name='notificacionA_inspeccion',
            field=models.CharField(max_length=255, verbose_name='Notificación'),
        ),
    ]
