# Generated by Django 5.2.7 on 2025-11-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdministrador', '0006_alter_tbl_inspeccion_notificaciona_inspeccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_unidad',
            name='orden',
            field=models.IntegerField(default=0, verbose_name='Orden'),
        ),
    ]
