# Generated by Django 5.2.7 on 2025-11-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdministrador', '0007_tbl_unidad_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_ccpp',
            name='clon_ccpp',
            field=models.CharField(blank=True, max_length=150, verbose_name='Clon'),
        ),
    ]
