# Generated by Django 5.2.7 on 2025-11-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdministrador', '0008_tbl_ccpp_clon_ccpp'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_inspeccion',
            name='color_inspeccion',
            field=models.CharField(default='#FFFFFF', max_length=10, verbose_name='Color de la Inspección'),
        ),
    ]
