# Generated by Django 5.2.7 on 2025-11-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdministrador', '0009_tbl_inspeccion_color_inspeccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_ccpp',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/', verbose_name='Imagen de la ccpp'),
        ),
    ]
