# Generated by Django 5.2.7 on 2025-11-08 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdministrador', '0010_tbl_ccpp_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Cronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anios', models.IntegerField(verbose_name='Años')),
                ('enero', models.IntegerField(default=0, verbose_name='Enero')),
                ('febrero', models.IntegerField(default=0, verbose_name='Febrero')),
                ('marzo', models.IntegerField(default=0, verbose_name='Marzo')),
                ('abril', models.IntegerField(default=0, verbose_name='Abril')),
                ('mayo', models.IntegerField(default=0, verbose_name='Mayo')),
                ('junio', models.IntegerField(default=0, verbose_name='Junio')),
                ('julio', models.IntegerField(default=0, verbose_name='Julio')),
                ('agosto', models.IntegerField(default=0, verbose_name='Agosto')),
                ('septiembre', models.IntegerField(default=0, verbose_name='Septiembre')),
                ('octubre', models.IntegerField(default=0, verbose_name='Octubre')),
                ('noviembre', models.IntegerField(default=0, verbose_name='Noviembre')),
                ('diciembre', models.IntegerField(default=0, verbose_name='Diciembre')),
                ('nota', models.CharField(blank=True, max_length=255, verbose_name='Nota')),
                ('ccpp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdministrador.tbl_ccpp', verbose_name='CCPP')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdministrador.tbl_unidad', verbose_name='Unidad')),
            ],
        ),
    ]
