# Generated by Django 5.2.7 on 2025-11-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdministrador', '0011_tbl_cronograma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_cronograma',
            name='abril',
            field=models.CharField(max_length=10, verbose_name='Abril'),
        ),
        migrations.AlterField(
            model_name='tbl_cronograma',
            name='agosto',
            field=models.IntegerField(max_length=10, verbose_name='Agosto'),
        ),
        migrations.AlterField(
            model_name='tbl_cronograma',
            name='diciembre',
            field=models.CharField(max_length=10, verbose_name='Diciembre'),
        ),
        migrations.AlterField(
            model_name='tbl_cronograma',
            name='enero',
            field=models.CharField(max_length=10, verbose_name='Enero'),
        ),
        migrations.AlterField(
            model_name='tbl_cronograma',
            name='febrero',
            field=models.CharField(max_length=10, verbose_name='Febrero'),
        ),
        migrations.AlterField(
            model_name='tbl_cronograma',
            name='julio',
            field=models.CharField(max_length=10, verbose_name='Julio'),
        ),
        migrations.AlterField(
            model_name='tbl_cronograma',
            name='junio',
            field=models.CharField(max_length=10, verbose_name='Junio'),
        ),
        migrations.AlterField(
            model_name='tbl_cronograma',
            name='marzo',
            field=models.CharField(max_length=10, verbose_name='Marzo'),
        ),
        migrations.AlterField(
            model_name='tbl_cronograma',
            name='mayo',
            field=models.CharField(max_length=10, verbose_name='Mayo'),
        ),
        migrations.AlterField(
            model_name='tbl_cronograma',
            name='noviembre',
            field=models.CharField(max_length=10, verbose_name='Noviembre'),
        ),
        migrations.AlterField(
            model_name='tbl_cronograma',
            name='octubre',
            field=models.CharField(max_length=10, verbose_name='Octubre'),
        ),
        migrations.AlterField(
            model_name='tbl_cronograma',
            name='septiembre',
            field=models.CharField(max_length=10, verbose_name='Septiembre'),
        ),
    ]
