# Generated by Django 5.2.7 on 2025-11-08 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAdministrador', '0013_alter_tbl_cronograma_abril_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_cronograma',
            name='nota',
        ),
    ]
