# Generated by Django 5.2.7 on 2025-11-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdministrador', '0014_remove_tbl_cronograma_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_cronograma',
            name='agosto',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Agosto'),
        ),
    ]
