# Generated by Django 5.2.7 on 2025-11-13 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdministrador', '0015_alter_tbl_cronograma_agosto'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('mes', models.CharField(max_length=20, verbose_name='Mes')),
                ('fecha', models.DateField(verbose_name='Fecha de Notificación')),
                ('para', models.TextField(verbose_name='Para')),
                ('cc', models.TextField(blank=True, verbose_name='CC')),
                ('cco', models.TextField(blank=True, verbose_name='CCO')),
                ('id_ccpp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdministrador.tbl_ccpp', verbose_name='CCPP')),
                ('id_inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdministrador.tbl_inspeccion', verbose_name='Inspección')),
                ('id_unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdministrador.tbl_unidad', verbose_name='Unidad')),
            ],
        ),
    ]
