# Generated by Django 5.2.7 on 2025-12-11 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdministrador', '0016_tbl_notificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=20, verbose_name='Mes')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha de Notificación')),
                ('para', models.TextField(blank=True, verbose_name='Para')),
                ('cc', models.TextField(blank=True, verbose_name='CC')),
                ('cco', models.TextField(blank=True, verbose_name='CCO')),
                ('FechaResp', models.DateField(blank=True, null=True, verbose_name='Fecha de Respuesta')),
                ('RespRevision', models.TextField(blank=True, verbose_name='Revisión de Respuesta')),
                ('RespControlador', models.TextField(blank=True, null=True, verbose_name='Controlador de Respuesta')),
                ('RespVia', models.TextField(blank=True, null=True, verbose_name='Via de Respuesta')),
                ('RespObservacion', models.TextField(blank=True, null=True, verbose_name='Observación de Respuesta')),
                ('RespInspEjecutada', models.BooleanField(default=False, verbose_name='Inspección Ejecutada')),
                ('NotificacionContestada', models.BooleanField(default=False, verbose_name='Notificación Contestada')),
                ('cronograma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appAdministrador.tbl_cronograma', verbose_name='Cronograma')),
                ('id_ccpp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdministrador.tbl_ccpp', verbose_name='CCPP')),
                ('id_inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdministrador.tbl_inspeccion', verbose_name='Inspección')),
                ('id_unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdministrador.tbl_unidad', verbose_name='Unidad')),
            ],
        ),
        migrations.CreateModel(
            name='NotificacionDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='notificaciones/documentos/%Y/%m/%d/')),
                ('nombre_original', models.CharField(max_length=255)),
                ('fecha_subida', models.DateField(auto_now_add=True)),
                ('tamano', models.BigIntegerField()),
                ('notificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='appAdministrador.notificacion')),
            ],
        ),
    ]
