# Generated by Django 5.2.7 on 2025-12-11 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdministrador', '0017_notificacion_notificaciondocumento'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precaucion', models.TextField(verbose_name='Precaución')),
                ('prescripcion', models.TextField(verbose_name='Prescripción')),
                ('prohibicion', models.TextField(verbose_name='Prohibición')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='imagenes_ficha/', verbose_name='Imagen de la ficha')),
                ('fecha_ficha', models.DateField(auto_now_add=True, verbose_name='Fecha de la Ficha')),
                ('id_unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdministrador.tbl_unidad')),
            ],
            options={
                'verbose_name': 'Detalle de Documento',
                'verbose_name_plural': 'Detalles de Documentos',
            },
        ),
        migrations.CreateModel(
            name='tbl_FichaControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_f', models.CharField(max_length=255, verbose_name='Período Ficha')),
                ('premisa_f', models.CharField(max_length=255, verbose_name='Premisa Ficha')),
                ('ejecutor_f', models.IntegerField(verbose_name='ID Ejecutor')),
                ('control_f', models.TextField(verbose_name='Control Ficha')),
                ('ejecutado_f', models.BooleanField(default=False, verbose_name='Ejecutado')),
                ('opacar_f', models.BooleanField(default=False, verbose_name='Opacar')),
                ('ocultar_f', models.BooleanField(default=False, verbose_name='Ocultar')),
                ('id_ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdministrador.tbl_ficha')),
            ],
            options={
                'verbose_name': 'Ficha de Control',
                'verbose_name_plural': 'Fichas de Control',
            },
        ),
    ]
