# Generated by Django 5.2.7 on 2025-12-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdministrador', '0018_tbl_ficha_tbl_fichacontrol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbl_ficha',
            options={},
        ),
        migrations.AddField(
            model_name='tbl_ficha',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos_ficha/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='tbl_ficha',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_ficha/', verbose_name='Imagen de anexo'),
        ),
    ]
