# Generated by Django 5.2.7 on 2025-12-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdministrador', '0019_alter_tbl_ficha_options_tbl_ficha_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_cronograma',
            name='nota',
            field=models.TextField(blank=True, null=True, verbose_name='Nota'),
        ),
    ]
