# Generated by Django 5.2.7 on 2025-12-14 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdministrador', '0020_tbl_cronograma_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_cronograma',
            name='ahora',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.DeleteModel(
            name='tbl_Notificacion',
        ),
    ]
