# Generated by Django 5.2.7 on 2025-12-15 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdministrador', '0021_tbl_cronograma_ahora_delete_tbl_notificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_fichacontrol',
            name='ejecutor_f',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appAdministrador.tbl_inspeccion', verbose_name='Inspección'),
        ),
    ]
