# Generated by Django 5.2.7 on 2025-12-17 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdministrador', '0022_alter_tbl_fichacontrol_ejecutor_f'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_ficha',
            name='id_ccpp',
            field=models.ForeignKey(default=48, on_delete=django.db.models.deletion.CASCADE, to='appAdministrador.tbl_ccpp'),
            preserve_default=False,
        ),
    ]
