# Generated by Django 5.2.7 on 2025-12-18 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdministrador', '0023_tbl_ficha_id_ccpp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_ficha',
            name='id_ccpp',
        ),
        migrations.AddField(
            model_name='tbl_ficha',
            name='titulo',
            field=models.CharField(default=1, max_length=255, verbose_name='Título de la Ficha'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='tbl_ficha_inspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_mes', models.CharField(max_length=50, verbose_name='Mes')),
                ('id_cronograma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appAdministrador.tbl_cronograma', verbose_name='Cronograma')),
                ('id_ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdministrador.tbl_ficha')),
                ('id_unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdministrador.tbl_unidad')),
            ],
        ),
    ]
