# Generated by Django 5.2.7 on 2025-12-19 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdministrador', '0024_remove_tbl_ficha_id_ccpp_tbl_ficha_titulo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbl_fichacontrol',
            options={},
        ),
        migrations.RenameField(
            model_name='tbl_ficha',
            old_name='id_unidad',
            new_name='FK_FichaUnidad',
        ),
        migrations.RenameField(
            model_name='tbl_ficha',
            old_name='fecha_ficha',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='tbl_fichacontrol',
            old_name='id_ficha',
            new_name='FK_FichaControl',
        ),
        migrations.RenameField(
            model_name='tbl_fichacontrol',
            old_name='ejecutor_f',
            new_name='FK_FichaControlInspeccion',
        ),
        migrations.RenameField(
            model_name='tbl_fichacontrol',
            old_name='control_f',
            new_name='control',
        ),
        migrations.RenameField(
            model_name='tbl_fichacontrol',
            old_name='ejecutado_f',
            new_name='ejecutado',
        ),
        migrations.RenameField(
            model_name='tbl_fichacontrol',
            old_name='ocultar_f',
            new_name='ocultar',
        ),
        migrations.RenameField(
            model_name='tbl_fichacontrol',
            old_name='opacar_f',
            new_name='opacar',
        ),
        migrations.RenameField(
            model_name='tbl_fichacontrol',
            old_name='periodo_f',
            new_name='periodo',
        ),
        migrations.RenameField(
            model_name='tbl_fichacontrol',
            old_name='premisa_f',
            new_name='premisa',
        ),
        migrations.RemoveField(
            model_name='tbl_ficha',
            name='titulo',
        ),
        migrations.AddField(
            model_name='tbl_ficha',
            name='PK_titulo',
            field=models.CharField(default='hola', max_length=255, unique=True, verbose_name='Título de la Ficha'),
            preserve_default=False,
        ),
    ]
