# Generated by Django 5.2.7 on 2025-12-19 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdministrador', '0025_alter_tbl_fichacontrol_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NotificacionDocumento',
            new_name='tbl_NotificacionDocumento',
        ),
        migrations.CreateModel(
            name='tbl_Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PK_mes', models.CharField(max_length=20, verbose_name='Mes')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha de Notificación')),
                ('para', models.TextField(blank=True, verbose_name='Para')),
                ('cc', models.TextField(blank=True, verbose_name='CC')),
                ('cco', models.TextField(blank=True, verbose_name='CCO')),
                ('FechaResp', models.DateField(blank=True, null=True, verbose_name='Fecha de Respuesta')),
                ('RespRevision', models.TextField(blank=True, verbose_name='Revisión de Respuesta')),
                ('RespControlador', models.TextField(blank=True, null=True, verbose_name='Controlador de Respuesta')),
                ('RespVia', models.TextField(blank=True, null=True, verbose_name='Via de Respuesta')),
                ('RespObservacion', models.TextField(blank=True, null=True, verbose_name='Observación de Respuesta')),
                ('RespInspEjecutada', models.BooleanField(default=False, verbose_name='Inspección Ejecutada')),
                ('NotificacionContestada', models.BooleanField(default=False, verbose_name='Notificación Contestada')),
                ('FK_cronograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='appAdministrador.tbl_cronograma', verbose_name='Cronograma Relacionado')),
                ('FK_inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdministrador.tbl_inspeccion', verbose_name='Inspección')),
            ],
        ),
        migrations.AlterField(
            model_name='tbl_notificaciondocumento',
            name='notificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='appAdministrador.tbl_notificacion'),
        ),
        migrations.DeleteModel(
            name='Notificacion',
        ),
    ]
