# Generated by Django 5.2.7 on 2025-12-19 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAdministrador', '0026_rename_notificaciondocumento_tbl_notificaciondocumento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_notificaciondocumento',
            old_name='notificacion',
            new_name='FK_notificacion',
        ),
    ]
