# Generated by Django 5.2.7 on 2025-12-21 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAdministrador', '0027_rename_notificacion_tbl_notificaciondocumento_fk_notificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_notificacion',
            name='FK_inspeccion',
        ),
    ]
