# Generated by Django 5.2.7 on 2025-12-21 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdministrador', '0028_remove_tbl_notificacion_fk_inspeccion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_ficha_inspeccion',
            old_name='id_ficha',
            new_name='FK_ficha',
        ),
        migrations.RenameField(
            model_name='tbl_ficha_inspeccion',
            old_name='id_mes',
            new_name='mes',
        ),
        migrations.RemoveField(
            model_name='tbl_ficha_inspeccion',
            name='id_cronograma',
        ),
        migrations.RemoveField(
            model_name='tbl_ficha_inspeccion',
            name='id_unidad',
        ),
        migrations.AddField(
            model_name='tbl_ficha_inspeccion',
            name='FK_cronograma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appAdministrador.tbl_cronograma', verbose_name='Cronograma'),
            preserve_default=False,
        ),
    ]
