# Generated by Django 5.2.7 on 2025-12-21 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdministrador', '0029_rename_id_ficha_tbl_ficha_inspeccion_fk_ficha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_notificacion',
            name='FK_ficha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appAdministrador.tbl_ficha', verbose_name='Ficha relacionada'),
        ),
        migrations.DeleteModel(
            name='tbl_ficha_inspeccion',
        ),
    ]
