# Generated by Django 5.2.7 on 2025-12-22 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdministrador', '0030_tbl_notificacion_fk_ficha_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbl_ficha',
            options={'verbose_name': 'Ficha', 'verbose_name_plural': 'Fichas'},
        ),
        migrations.AlterModelOptions(
            name='tbl_fichacontrol',
            options={'verbose_name': 'Control de Ficha', 'verbose_name_plural': 'Controles de Ficha'},
        ),
        migrations.AlterField(
            model_name='tbl_fichacontrol',
            name='FK_FichaControl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles', to='appAdministrador.tbl_ficha'),
        ),
    ]
