# Generated by Django 5.2.7 on 2025-12-22 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdministrador', '0031_alter_tbl_ficha_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbl_ficha',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tbl_fichacontrol',
            options={},
        ),
        migrations.AlterField(
            model_name='tbl_fichacontrol',
            name='FK_FichaControl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdministrador.tbl_ficha'),
        ),
    ]
