# Generated by Django 5.2.7 on 2025-12-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdministrador', '0033_alter_tbl_notificaciondocumento_options_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servidor_smtp', models.CharField(default='smtp.gmail.com', max_length=255)),
                ('puerto', models.IntegerField(default=587)),
                ('usar_tls', models.BooleanField(default=True)),
                ('usuario_email', models.EmailField(max_length=255)),
                ('password_aplicacion', models.CharField(help_text='Usa la contraseña de aplicación, no la personal.', max_length=255)),
            ],
            options={
                'verbose_name': 'Configuración de Email',
                'verbose_name_plural': 'Configuraciones de Email',
            },
        ),
    ]
