# Generated by Django 5.2.7 on 2025-12-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdministrador', '0034_configuracionemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_notificacion',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de Notificación'),
        ),
    ]
